---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by arieh.
--- DateTime: 5/25/18 7:43 AM
---

local TMW_ST = TMW_Script_Tools

function TMW_ST:InitCounter(name, initialValue)
    TMW_ST:printDebug("Initializing Counter", name, initialValue)
    TMW.COUNTERS[name] = initialValue or 0
end

function TMW_ST:UpdateCounter(name, value)
    TMW_ST:printDebug("Setting Counter Value", name, value)
    TMW.COUNTERS[name] = value
    TMW:Fire("TMW_COUNTER_MODIFIED", name)
end

function TMW_ST:GetCounter(name)
    return TMW.COUNTERS[name]
end
