---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by arieh.
--- DateTime: 5/25/18 7:45 AM
---

local TMW_ST = TMW_Script_Tools
local DogTag = LibStub("LibDogTag-3.0", true)
local TMW = TMW

TMW_ST.ScriptTexts = {}
 
TMW:RegisterCallback("TMW_ST_VARIABLE_MODIFIED", DogTag.FireEvent, DogTag)

function TMW_ST:SetScriptText(name, text)
    TMW_ST.ScriptTexts[name] = text
    TMW:Fire("TMW_ST_VARIABLE_MODIFIED", name)
end

if DogTag then
    DogTag:AddTag("TMW", "ST_GetScriptText", {
        code = function(name)
            return TMW_ST.ScriptTexts[name] or ""
        end,
        arg = {
            'name', 'string', '@req',
        },
        ret = "string",
        doc = "Return the value of a script variable",
        example = '[ST_GetScriptText("var1")] => "my var"',
        events = "TMW_ST_VARIABLE_MODIFIED",
        category = "Userland"
    })
end